
CREATE TABLE "user"
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    isRegistered BOOLEAN
);


CREATE TABLE session
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
);


CREATE TABLE admin
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
);


CREATE TABLE comment
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR,
    date TIMESTAMP,
    user_id INTEGER,
    admin_id INTEGER
);


CREATE TABLE post
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50),
    content VARCHAR(200),
    date TIMESTAMP,
    admin_id INTEGER
);

ALTER TABLE admin
    ADD CONSTRAINT fk_admin
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

ALTER TABLE session
    ADD CONSTRAINT fk_user_session
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

ALTER TABLE comment
    ADD CONSTRAINT fk_user_comment
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

ALTER TABLE comment
    ADD CONSTRAINT fk_admin_comment
        FOREIGN KEY (admin_id)
            REFERENCES admin (id);

ALTER TABLE post
    ADD CONSTRAINT fk_admin_post
        FOREIGN KEY (admin_id)
            REFERENCES admin (id);